spring.application.name=SMARTWAREHOUSE

spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.threads.virtual.enabled=true

# OpenAI Configuration
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.google.genai.api-key=AQ.Ab8RN6IvhysfTBHyhyAIyRXqAs9NV1Fik1oSDtphc5ncF2Y9JA
spring.ai.google.genai.chat.options.model=gemini-3.6-flash